### PR TITLE
Fix deprecated sbt methods in Build.scala

### PR DESCRIPTION
**Pull request by monkey-mas**
### Problem

There're 5 warning logs related to usage of deprecated sbt methods.

### Solution

We can modify deprecated methods as each warning indicates;

1. replaced `<<=` with `:=`
```
[warn] util/project/Build.scala:90: `<<=` operator is deprecated. Use `key := { x.value }` or `key ~= (old => { newValue })`.
[warn] See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
[warn]     publishTo <<= version { (v: String) =>
[warn]               ^
```

2. replaced `<+=` with `+=`
```
[warn] util/project/Build.scala:189: `<+=` operator is deprecated. Try `lhs += { x.value }`
[warn]   or see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html.
[warn]     resourceGenerators in Compile <+=
[warn]                                   ^
```

3. replaced `<++=` with `++=`
```
[warn] util/project/Build.scala:204: `<++=` operator is deprecated. Try `lhs ++= { x.value }`
[warn]   or see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html.
[warn]       scalacOptions in doc <++= version.map(v => Seq("-doc-title", "Util", "-doc-version", v)),
[warn]                            ^
```

4. fixed `(k1, k2) map { (x, y) => ... }`
```
[warn] util/project/Build.scala:190: method t3ToTable3 in object Scoped is deprecated: The sbt 0.10 style DSL is deprecated: `(k1, k2) map { (x, y) => ... }` should now be `{ val x = k1.value; val y = k2.value }`.
[warn] See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
[warn]       (resourceManaged in Compile, name, version) map { (dir, name, ver) =>
```

### Result

One last warning is left as follows:
```
[warn] util/project/Build.scala:10: trait Build in package sbt is deprecated: Use .sbt format instead
[warn] object Util extends Build {
[warn]                     ^
```

### CODE REVIEW

**Comment by mosesn** [comment]
Thanks for the review @monkey-mas!

**Comment by monkey-mas** [comment]
@mosesn Sorry, I’ve done additional fix :( Can you please review it again?

```diff
-    publishTo := (version { (v: String) =>
+    publishTo := {
       val nexus = "https://oss.sonatype.org/"
-      if (v.trim.endsWith("SNAPSHOT"))
+      if (version.value.trim.endsWith("SNAPSHOT"))
         Some("snapshots" at nexus + "content/repositories/snapshots")
       else
         Some("releases"  at nexus + "service/local/staging/deploy/maven2")
-    }).value
+    }
```

```diff
-      scalacOptions in doc ++= version.map(v => Seq("-doc-title", "Util", "-doc-version", v)).value,
+      scalacOptions in doc ++= Seq("-doc-title", "Util", "-doc-version", version.value),
```

**Comment by jcrossley** [comment]
LGTM

**Comment by jcrossley** [comment]
@monkey-mas this has been merged internally and will go out with the next release. Thanks for your contribution!

**Comment by monkey-mas** [comment]
Thanks for your review!

**Pull request closed without merging**
