### PR TITLE
util-core: improve test coverage for Cancellable

### PR DESCRIPTION
**Pull request by muachilin**
Problem

The test coverage of Cancellable still needs to be improved. Particularly the object of Cancellable has not been tested.

Solution

Add more tests for Cancellable.

Result

Improve the test coverage for Cancellable.

### CODE REVIEW

**Comment by muachilin** [comment]
Hello @ryanoneill , I created a new pull request with only the file changes for testing Cancellable. Would you please check whether the patch is clean or not? Thank you very much!

**Comment by ryanoneill** [comment]
Thank you. I'm handling this internally now. I'll post back when the commit has been pushed back to GitHub.

**Comment by ryanoneill** [comment]
Thanks again @muachilin. This was pushed back out to GitHub as commit https://github.com/twitter/util/commit/41227fa84087375ae8d1def4c04eadaba64f30e5

**Comment by muachilin** [comment]
Thank you :)

**Pull request closed without merging**
