### PR TITLE
Happy first day Flavio!

### PR DESCRIPTION
**Pull request by folone**
Here's an embarassing pull request to celebrate your first day at twitter @fwbrasil!

Love, your former colleagues: @folone, @grandbora, @samstarling, @missingfaktor, @herval, and everyone else here at @soundcloud!

Have fun there!

kraken

### CODE REVIEW

**Comment by samstarling** [comment]
:+1:

**Comment by grandbora** [comment]
HAHA
:+1:

**Comment by ccmtaylor** [comment]
:+1:

**Comment by missingfaktor** [comment]
:+1:

**Comment by travisbrown** [comment]
:+1:, but only after @fwbrasil has migrated the entire internal codebase / build to TLC. :smile:

**Comment by mosesn** [comment]
LGTM

**Comment by herval** [comment]
💪👽👍

**Comment by williamboxhall** [comment]
:+1:

**Comment by garriguv** [comment]
:+1: :clap:

**Comment by fwbrasil** [comment]
That's a good way to start at a new job, being trolled by your friends. Thanks guys, I'll miss you! :)

I suggest closing this PR for now, ALL CHECKS HAVE FAILED.

**Comment by folone** [comment]
CLOSING NAO
aye aye captn

**Comment by grandbora** [comment]
superseded by https://github.com/twitter/util/pull/205

**Pull request closed without merging**
