### PR TITLE
Happy first FOLONE day!

### PR DESCRIPTION
**Pull request by grandbora**
This is a throw back to https://github.com/twitter/util/pull/141!

Dear fellow SC crew, join me celebrating @folone's first day at Twitter. @fwbrasil @herval @williamboxhall @missingfaktor @samstarling @janogonzalez @garriguv @argha-c @chrisberkhout @alonpeer

Hey @folone here is a set of embarrassing photos to make you popular in your new company.

fol
screen shot 2017-11-13 at 18 54 24
img_2412

❤️  from former SoundClouders. All the best in twitter.

### CODE REVIEW

**Comment by fwbrasil** [comment]
Welcome @folone!!

> Merging #205 into develop will decrease coverage by 0.02%

**Comment by garriguv** [comment]
:shipit:

**Comment by alonpeer** [comment]
🐑 IT!

**Comment by janogonzalez** [comment]
🐸 🐶

**Comment by folone** [comment]
@grandbora please test your change properly: we cannot afford to drop our coverage percentage by so much!

**Comment by williamboxhall** [comment]
👎 due to long hair, otherwise :shipit:

**Comment by chrisberkhout** [comment]
:+1: :frog: :dog: :tada:

**Comment by missingfaktor** [comment]
LGTM! (All the best, @folone!)

**Comment by argha-c** [comment]
LGTM. (Keep 🏃 ahead @folone!)

**Comment by folone** [comment]
Thanks, everyone!

**Pull request closed without merging**
